name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
