name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  testsyarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test

  testsnpm:
    needs: testsyarn
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        