name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: mskelton/setup-yarn@v1
      - name: Set up yarn
        uses: mskelton/setup-yarn@v1
            with:
                node-version: '16.x'
      - name: flags for install command
        uses: mskelton/setup-yarn@v1
              with:
              flags: --immutable-cache
      - name: Install dependencies
        run: yarn add
      - name: Run tests
        run: yarn test
